server:
  port: 8083

spring:
  application:
    name: msvc-sensors
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/sensor_db
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    database_platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: 1234
  amqp:
    deserialization:
      trust:
        all: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

fanout:
  exchange: servidor_invernadero
  queue: queue-sensor

rabbitmq:
  exchange:
    name: exchange-servicios
  sensor:
    queue:
      name: queue-servicio-sensor
    routing:
      key: servicio-sensor
  invernadero:
    queue:
      name: queue-servicio-invernadero
    routing:
      key: servicio-invernadero
  alarma:
    queue:
      name: queue-servicio-alarma
    routing:
      key: servicio-alarma




