/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.simulador_sensores.view;

import com.mycompany.simulador_sensores.data.DataSen;
import com.mycompany.simulador_sensores.data.impl.HumidityData;
import com.mycompany.simulador_sensores.data.impl.TemperatureData;
import com.mycompany.simulador_sensores.facade.SensorFacade;
import com.mycompany.simulador_sensores.facade.impl.SensorFacadeImpl;
import com.mycompany.simulador_sensores.protocol.Protocol;
import com.mycompany.simulador_sensores.protocol.impl.CoapProtocol;
import com.mycompany.simulador_sensores.protocol.impl.MqttProtocol;
import com.mycompany.simulador_sensores.sensor.Sensor;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Diego
 */
public final class PantallaSensores extends javax.swing.JFrame {

    private final SensorFacade sensorFacade = new SensorFacadeImpl();
    private boolean btnSensoresSelecionado = false;
    private RegistroSensorView registroSensorView;
    private List<Sensor> sensores;
    private final List<Sensor> sensoresActivos = new ArrayList<>();

    public PantallaSensores() {
        initComponents();
        validarTitulo();
        cargarDatosTabla();
        this.tblSensores.setBackground(Color.RED);
        this.tblSensores.setSelectionBackground(Color.RED);
        registroSensorView = new RegistroSensorView(this);
    }

    private void validarTitulo() {
        if (btnSensoresSelecionado == false) {
            this.txtTitulo.setText("Sensores Desactivados");
        } else if (btnSensoresSelecionado == true) {
            this.txtTitulo.setText("Sensores Activados");
        }
    }

    protected void cargarDatosTabla() {
        sensores = sensorFacade.readAllSensors();
        DefaultTableModel model = (DefaultTableModel) tblSensores.getModel();
        model.setRowCount(0);
        for (Sensor sensor : sensores) {
            model.addRow(crearObjetoTabla(sensor));
        }
    }

    private Object[] crearObjetoTabla(Sensor sensor) {
        String serie = sensor.getSerie();
        boolean estatus = sensor.isStatus();
        String protocolo = validarProtocolo(sensor.getProtocol());
        List<String> mediciones = validarTipoMedicion(sensor.getData());
        int tiempoCaptura = sensor.getTimeInterval();

        if (mediciones.size() == 2) {
            return new Object[]{serie, estatus,
                protocolo, mediciones.get(0), mediciones.get(1),
                tiempoCaptura};
        } else {
            return new Object[]{serie, estatus,
                protocolo, mediciones.get(0), "",
                tiempoCaptura};
        }

    }

    private List<String> validarTipoMedicion(List<DataSen> data) {
        List<String> mediciones = new ArrayList<>();
        for (DataSen dataImp : data) {
            if (dataImp instanceof HumidityData) {
                mediciones.add("Humedad "
                        + ((HumidityData) dataImp).getHumidityUnit().toString());
            } else if (dataImp instanceof TemperatureData) {
                mediciones.add("Temperatura "
                        + ((TemperatureData) dataImp).getTemperatureUnit().toString());
            }
        }
        return mediciones;
    }

    private String validarProtocolo(Protocol protocol) {
        if (protocol instanceof CoapProtocol) {
            return "COAP";
        } else if (protocol instanceof MqttProtocol) {
            return "MQTT";

        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tab1 = new javax.swing.JPanel();
        btnIniciarSensores = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnRegistrar = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSensores = new javax.swing.JTable();
        txtTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(221, 208, 200));

        tab1.setBackground(new java.awt.Color(50, 50, 50));
        tab1.setForeground(new java.awt.Color(60, 63, 65));

        btnIniciarSensores.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnIniciarSensores.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciarSensores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnIniciarSensores.setText("Iniciar Sensores");
        btnIniciarSensores.setVerifyInputWhenFocusTarget(false);
        btnIniciarSensores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIniciarSensoresMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout tab1Layout = new javax.swing.GroupLayout(tab1);
        tab1.setLayout(tab1Layout);
        tab1Layout.setHorizontalGroup(
            tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab1Layout.createSequentialGroup()
                .addComponent(btnIniciarSensores, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        tab1Layout.setVerticalGroup(
            tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnIniciarSensores, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sensor.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Sensores");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Simulador ");

        jPanel3.setBackground(new java.awt.Color(50, 50, 50));
        jPanel3.setForeground(new java.awt.Color(60, 63, 65));

        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnRegistrar.setText("Registar Sensor");
        btnRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(8, 8, 8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(tab1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(142, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 600));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        tblSensores.setBackground(new java.awt.Color(255, 255, 255));
        tblSensores.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tblSensores.setForeground(new java.awt.Color(0, 0, 0));
        tblSensores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serie", "Estatus", "Protocolo", "Tipo de Medición", "", "Intervalo de Captura"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSensores.setFocusable(false);
        tblSensores.setRowHeight(25);
        tblSensores.setSelectionBackground(new java.awt.Color(60, 63, 65));
        tblSensores.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tblSensores.setShowGrid(false);
        tblSensores.getTableHeader().setResizingAllowed(false);
        tblSensores.getTableHeader().setReorderingAllowed(false);
        tblSensores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSensoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSensores);
        if (tblSensores.getColumnModel().getColumnCount() > 0) {
            tblSensores.getColumnModel().getColumn(0).setResizable(false);
            tblSensores.getColumnModel().getColumn(0).setPreferredWidth(5);
            tblSensores.getColumnModel().getColumn(1).setResizable(false);
            tblSensores.getColumnModel().getColumn(1).setPreferredWidth(5);
            tblSensores.getColumnModel().getColumn(5).setResizable(false);
            tblSensores.getColumnModel().getColumn(5).setPreferredWidth(10);
        }

        txtTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtTitulo.setForeground(new java.awt.Color(0, 0, 0));
        txtTitulo.setText("jLabel3");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(14, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 753, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(txtTitulo)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 790, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarSensoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIniciarSensoresMouseClicked
        // TODO add your handling code here:
        if (!btnSensoresSelecionado) {
            btnSensoresSelecionado = true;
            this.tblSensores.setBackground(Color.GREEN);
            this.tblSensores.setSelectionBackground(Color.GREEN);
            inciarSensores();
        } else {
            this.btnSensoresSelecionado = false;
            this.tblSensores.setBackground(Color.RED);
            this.tblSensores.setSelectionBackground(Color.RED);
            pararSensores();
        }
        validarTitulo();
        cargarDatosTabla();
    }//GEN-LAST:event_btnIniciarSensoresMouseClicked

    private void inciarSensores() {
        for (Sensor sensor : sensores) {
            sensoresActivos.add(sensor);
            sensor.startSensor();
            sensorFacade.updateSensor(sensor);
        }
    }

    private void pararSensores() {
        for (Sensor sensor : sensoresActivos) {
            sensor.stopSensor();
            sensorFacade.updateSensor(sensor);
        }
        sensoresActivos.clear();
    }
    private void btnRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        registroSensorView.setVisible(true);
    }//GEN-LAST:event_btnRegistrarMouseClicked

    private void tblSensoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSensoresMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            int filaSeleccionada = tblSensores.rowAtPoint(evt.getPoint());
            if (filaSeleccionada != -1) {
                mostrarDialogoEmergente(filaSeleccionada);
            }
        }
    }//GEN-LAST:event_tblSensoresMouseClicked

    private void mostrarDialogoEmergente(int filaSeleccionada) {
        Object[] opciones = {"Eliminar", "Actualizar", "Cancelar"};

        String serie = tblSensores.getValueAt(filaSeleccionada, 0).toString();
        int seleccion = JOptionPane.showOptionDialog(
                this,
                "¿Qué acción deseas realizar en la fila seleccionada?",
                "Selecciona una acción",
                JOptionPane.YES_NO_CANCEL_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                opciones,
                opciones[2]);

        if (seleccion == JOptionPane.YES_OPTION) {
            eliminarSensor(serie);
        } else if (seleccion == JOptionPane.NO_OPTION) {

        }

    }

    private void eliminarSensor(String serie) {
        try {
            sensorFacade.deleteSensor(serie);
            cargarDatosTabla();

        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error al guardar el sensor", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error inesperado: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    @Override
    public void dispose() {
        super.dispose();
        pararSensores();
        System.exit(0);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnIniciarSensores;
    private javax.swing.JLabel btnRegistrar;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel tab1;
    public javax.swing.JTable tblSensores;
    private javax.swing.JLabel txtTitulo;
    // End of variables declaration//GEN-END:variables
}
